tokenizer_path: gslm_tokenizer_dac_tts/tokenizer.json
dataset:
  folder: /mnt/hdd/datasets/libritts/
  train:
    pattern: dac_quantized_train.txt
  dev:
    pattern: dac_quantized_dev.txt
  test:
    pattern: dac_quantized_test.txt
output_json_tts:
  train: /mnt/hdd/GSLM/train_dac_tts0215.jsonl
  valid: /mnt/hdd/GSLM/valid_dac_tts0215.jsonl
  test: /mnt/hdd/GSLM/test_dac_tts0215.jsonl
output_json:
  train: /mnt/hdd/GSLM/train_dac.jsonl
  valid: /mnt/hdd/GSLM/valid_dac.jsonl
  test: /mnt/hdd/GSLM/test_dac.jsonl

output_json_tts_t5:
  train: dac_libri/train.jsonl
  valid: dac_libri/dev.jsonl
  test:  dac_libri/test.jsonl
librilight:
  manifest_root: /home/wnakata/librilight_cleaning/notebooks/output/
  manifest_pattern: libriheavy_cuts_*.jsonl.gz
  feature_root: /home/wnakata/GSLM/fairseq_manifest/
  feature_pattern: libriheavy_cuts_*.txt_dac_quantized_l0_km1000.feature
  output_jsonl_path: ???

ljspeech:
  manifest_root: /mnt/hdd/datasets/LJSpeech-1.1/
  feature_file_suffix: txt_dac_quantized_l0_km1000.feature
  dataset_path: lj_speech_dac/