tokenizer_path: gslm_tokenizer_hubert_tts/tokenizer.json
dataset:
  folder: /mnt/hdd/datasets/libritts/
  train:
    pattern: hubert_quantized_train.txt
  dev:
    pattern: hubert_quantized_dev.txt
  test:
    pattern: hubert_quantized_test.txt
output_json_tts:
  train: /mnt/hdd/GSLM/train_hubert_tts.jsonl
  valid: /mnt/hdd/GSLM/valid_hubert_tts.jsonl
  test: /mnt/hdd/GSLM/test_hubert_tts.jsonl
output_json:
  train: /mnt/hdd/GSLM/train_hubert.jsonl
  valid: /mnt/hdd/GSLM/valid_hubert.jsonl
  test: /mnt/hdd/GSLM/test_hubert.jsonl
librilight:
  manifest: /home/wnakata/librilight_cleaning/notebooks/output/libriheavy_cuts_0.jsonl.gz
  feature_path: /home/wnakata/GSLM/fairseq_manifest/libriheavy_cuts_0.txt_hubert_quantized_l6_km1000.feature
  output_jsonl_path: ???