tokenizer_path: gslm_tokenizer_hubert/tokenizer.json
dataset:
  folder: /mnt/hdd/datasets/libritts/
  train:
    pattern: necobert_quantized_train.txt
  dev:
    pattern: necobert_quantized_dev.txt
  test:
    pattern: necobert_quantized_test.txt
output_json_tts:
  train: /mnt/hdd/GSLM/train_necobert_tts0215.jsonl
  valid: /mnt/hdd/GSLM/valid_necobert_tts0215.jsonl
  test: /mnt/hdd/GSLM/test_necobert_tts0215.jsonl

output_json:
  train: /mnt/hdd/GSLM/train_necobert.jsonl
  valid: /mnt/hdd/GSLM/valid_necobert.jsonl
  test: /mnt/hdd/GSLM/test_necobert.jsonl
librilight:
  manifest_root: /home/wnakata/librilight_cleaning/notebooks/output/
  manifest_pattern: libriheavy_cuts_*.jsonl.gz
  feature_root: /home/wnakata/GSLM/fairseq_manifest/
  feature_pattern: libriheavy_cuts_*.txt_necobert_masked_quantized_l12_km1000.feature
  output_jsonl_path: ???

ljspeech:
  manifest_root: /mnt/hdd/datasets/LJSpeech-1.1/
  feature_file_suffix: txt_necobert_quantized_l12_km1000.feature
  dataset_path: lj_speech_necobert/