tokenizer_path: gslm_tokenizer_necobert_masked_l6/tokenizer.json
dataset:
  folder: /mnt/hdd/datasets/libritts/
  train:
    pattern: necobert_quantized_masked_l6_train.txt
  dev:
    pattern: necobert_quantized_masked_l6_dev.txt
  test:
    pattern: necobert_quantized_masked_l6_test.txt
output_json_tts:
  train: /mnt/hdd/GSLM/train_necobert_masked_l6_tts.jsonl
  valid: /mnt/hdd/GSLM/valid_necobert_masked_l6_tts.jsonl
  test: /mnt/hdd/GSLM/test_necobert_masked_l6_tts.jsonl

output_json:
  train: /mnt/hdd/GSLM/train_necobert_masked_l6.jsonl
  valid: /mnt/hdd/GSLM/valid_necobert_masked_l6.jsonl
  test: /mnt/hdd/GSLM/test_necobert_masked_l6.jsonl